version: 0.2

phases:
  install:
    commands:
      - echo install serverless framework
      - npm install -g serverless
  pre_build:
    commands:
      - echo install pre build commands
      - npm install --no-optional
      - cd layers/logger/nodejs/node_modules/logger
      - npm run compile
      - cd ../../../..
  build:
    commands:
      - echo deployment started `date`
      - echo deploy serverless framework custom codebase
      - npm run deploy
  post_build:
    commands:
      - echo post build completed on `date`