service: layers
frameworkVersion: '3'
plugins:
  - serverless-esbuild
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  stage: dev
  versionFunctions: true
  iamRoleStatements:
      - Effect: Allow
        Action: 
          - cloudformation:DescribeStacks
        Resource: 
          - arn:aws:cloudformation:${self:provider.region}:*

package:
  individually: true
  artifactsS3KeyDirname: serverless/layers/dev/code-artifacts
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    define: {}
    platform: node
    concurrency: 10
layers:
  logger:
    path: logger

resources:
  Outputs:
    customeLogger:
      Value:
        Ref: LoggerLambdaLayer
      Export:
        Name: LoggerLambdaLayer