openapi: 3.0.0
components:
  schemas: {}
  securitySchemes: {}
info:
  title: My API
  description: This is my API
  version: '1'
paths:
  /hello:
    get:
      operationId: hello
      summary: Register a new user.
      responses: {}
