// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "serverless-typescript",
    "version": "1"
  },
  "paths": {
    "/hello": {
      "get": {
        "summary": "hello",
        "description": "",
        "operationId": "hello.get.hello",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/error": {
      "get": {
        "summary": "errorTest",
        "description": "",
        "operationId": "errorTest.get.error",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/users/": {
      "post": {
        "summary": "createUser",
        "description": "",
        "operationId": "createUser.post.users/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "getUsers",
        "description": "",
        "operationId": "getUsers.get.users/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "300": {
            "description": "Test response"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "getUserById",
        "description": "",
        "operationId": "getUserById.get.users/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/schedule": {
      "get": {
        "summary": "createSchedule",
        "description": "",
        "operationId": "createSchedule.get.schedule",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/cloudformation": {
      "get": {
        "summary": "getCloudFormationOutput",
        "description": "",
        "operationId": "getCloudFormationOutput.get.cloudformation",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/messages/{proxy+}": {
      "any": {
        "summary": "expressRoutes",
        "description": "",
        "operationId": "expressRoutes.any./messages/{proxy+}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proxy+",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/sendMessage": {
      "get": {
        "summary": "sendMessage",
        "description": "",
        "operationId": "sendMessage.get.sendMessage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/preSigned": {
      "post": {
        "summary": "preSigned",
        "description": "",
        "operationId": "preSigned.post.preSigned",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};